#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Release

#Additional flags
PREPROCESSOR_MACROS := NDEBUG=1 RELEASE=1 USE_HAL_DRIVER STM32F429xx
INCLUDE_DIRS := ../Core/Inc \
  ../Drivers/BSP \
  ../Drivers/CMSIS/Device/ST/STM32F4xx/Include \
  ../Drivers/CMSIS/Include \
  ../Drivers/STM32F4xx_HAL_Driver/Inc \
  ../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
  ../Middlewares/ST/touchgfx/3rdparty/libjpeg/include \
  ../Middlewares/ST/touchgfx/framework/include \
  ../Middlewares/ST/touchgfx/framework/include/platform/hal/simulator/sdl2/vendor \
  ../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
  ../Middlewares/Third_Party/FreeRTOS/Source/include \
  ../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
  ../Middlewares/Third_Party/FreeRTOS/Source/portable/IAR/ARM_CM4F \
  ../Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F \
  ../TouchGFX/App \
  ../TouchGFX/target \
  ../TouchGFX/target/generated \
  ../TouchGFX/generated/fonts/include \
  ../TouchGFX/generated/gui_generated/include \
  ../TouchGFX/generated/images/include \
  ../TouchGFX/generated/texts/include \
  ../TouchGFX/generated/videos/include \
  ../TouchGFX/gui/include
LIBRARY_DIRS := 
LIBRARY_NAMES := 
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O3
CXXFLAGS := -std=c++1z -ggdb -ffunction-sections -fno-exceptions -fno-rtti -O3
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 
LINKER_SCRIPT := ../gcc/STM32F429ZITX_FLASH.ld

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
USE_DEL_TO_CLEAN := 1
CP_NOT_AVAILABLE := 1

ADDITIONAL_MAKE_FILES := stm32.mak
GENERATE_BIN_FILE := 1
GENERATE_IHEX_FILE := 1
