#This file is generated by VisualGDB.
#It contains GCC settings automatically derived from the board support package (BSP).
#DO NOT EDIT MANUALLY. THE FILE WILL BE OVERWRITTEN. 
#Use VisualGDB Project Properties dialog or modify Makefile or per-configuration .mak files instead.

TESTFW_BASE_LOCAL := ../TestFrameworks

INCLUDE_DIRS += \
  $(TESTFW_BASE_LOCAL)/cpputest/include \
  $(TESTFW_BASE_LOCAL)/cpputest/Platforms \
  $(TESTFW_BASE_LOCAL)/unity/src \
  $(TESTFW_BASE_LOCAL)/unity/extras/fixture/src \
  $(TESTFW_BASE_LOCAL)/unity/extras/memory/src

PREPROCESSOR_MACROS += 
