#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Additional flags
PREPROCESSOR_MACROS := DEBUG=1 ST USE_BPP=16 CORE_CM4F USE_FULL_ASSERT USE_HAL_DRIVER STM32F429xx
INCLUDE_DIRS := \
  ../Core/Inc \
  ../Drivers/BSP \
  ../Drivers/CMSIS/Device/ST/STM32F4xx/Include \
  ../Drivers/CMSIS/Include \
  ../Drivers/STM32F4xx_HAL_Driver/Inc \
  ../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
  ../Middlewares/ST/threadx/common/inc \
  ../Middlewares/ST/threadx/ports/cortex_m4/gnu/inc \
  ../Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc \
  ../Middlewares/ST/STM32_USB_Device_Library/Core/Inc \
  ../Middlewares/Third_Party/FatFs/src \
  ../TouchGFX/App \
  ../FATFS/App \
  ../FATFS/Target \
  ../USB_DEVICE/App \
  ../USB_DEVICE/Target \
  ../TouchGFX/target \
  ../TouchGFX/target/generated \
  ../Middlewares/ST/touchgfx/framework/include \
  ../TouchGFX/generated/fonts/include \
  ../TouchGFX/generated/gui_generated/include \
  ../TouchGFX/generated/images/include \
  ../TouchGFX/generated/texts/include \
  ../TouchGFX/generated/videos/include \
  ../TouchGFX/gui/include \
  ../Middlewares/ST/touchgfx/3rdparty/libjpeg/include \
  ../Middlewares/ST/touchgfx/framework/include \

LIBRARY_DIRS := 
LIBRARY_NAMES := 
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O0
CXXFLAGS := -std=c++1z -ggdb -ffunction-sections -fno-exceptions -fno-rtti -O0
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 
LINKER_SCRIPT := ../gcc/STM32F429ZITX_FLASH.ld

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
USE_DEL_TO_CLEAN := 1
CP_NOT_AVAILABLE := 1

ADDITIONAL_MAKE_FILES := stm32.mak
GENERATE_BIN_FILE := 1
GENERATE_IHEX_FILE := 1
